module Main.Run.Eulers(getEuler) where
-- Do not edit this file manually! Instead use --generate/-g N or --delete/-d N to modify this file.
import Data.List(find)
import Solutions.Euler001(euler001)

eulers :: [(Int, IO String)]
eulers =
    [ (1, euler001)
    ]

getEuler :: Int -> Maybe (IO String)
getEuler problemNo = snd <$> find ((==problemNo) . fst) eulers
